spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:file:/data1/h2/app-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  web:
    resources:
      add-mappings: true

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG