frontend.url=http://localhost:3000
REDIRECT_URL=http://localhost:8080/login/oauth2/code/google
app.jwt.secret=
app.jwt.expirationMillis=900000
app.jwt.refreshExpirationMillis=604800000

#DB properties
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect