frontend.url=https://myfrontend.example.com
REDIRECT_URL=https://TranscationTrackerALB-358002547.us-east-1.elb.amazonaws.com/login/oauth2/code/google
spring.config.import=aws-secretsmanager:myapp/prod/config