MERGE INTO "PUBLIC"."CATEGORIES" (ID, NAME, DESCRIPTION)
    KEY(ID)
    VALUES
        (1, 'Household & Utilities', NULL),
        (2, 'EMI', NULL),
        (3, 'Investments', NULL),
        (4, 'Miscellaneous', NULL),
        (5, 'Health & Personal Care', NULL),
        (6, 'Education', NULL),
        (7, 'Quick Commerce', NULL),
        (8, 'Food', NULL),
        (9, 'Lifestyle & Entertainment', NULL),
        (10, 'Credit', NULL);

MERGE INTO "PUBLIC"."SUBCATEGORIES" (ID, CATEGORY_ID, NAME, DESCRIPTION)
    KEY(ID)
    VALUES
        (1, 1, 'Groceries(offline)', NULL),
        (2, 1, 'Vegetables/Fruits(offline)', NULL),
        (3, 1, 'Utilities', NULL),
        (4, 1, 'Society Maintenance', NULL),
        (5, 1, 'House Help', NULL),
        (6, 1, 'Transport', NULL),
        (7, 1, 'Service/Repairs', NULL),
        (8, 1, 'Adhoc', NULL),
        (9, 2, 'EMI', NULL),
        (10, 3, 'Investments', NULL),
        (11, 4, 'Others', NULL),
        (12, 5, 'Medicial', NULL),
        (13, 5, 'Saloon', NULL),
        (14, 5, 'Skin Care products', NULL),
        (15, 5, 'Doctor Visits', NULL),
        (16, 5, 'Vaccination', NULL),
        (17, 6, 'Stationary', NULL),
        (18, 6, 'School Activities Fees', NULL),
        (19, 6, 'School fees', NULL),
        (20, 6, 'Tuition fees', NULL),
        (21, 7, 'Zepto', NULL),
        (22, 7, 'Swiggy', NULL),
        (23, 7, 'BBDaily', NULL),
        (24, 7, 'Others', NULL),
        (25, 8, 'Zomato/Swiggy', NULL),
        (26, 8, 'Prashant Corner', NULL),
        (27, 8, 'Restaurants/Dine In', NULL),
        (28, 9, 'Clothes', NULL),
        (29, 9, 'Electronics', NULL),
        (30, 9, 'Accessories', NULL),
        (31, 9, 'Entertainment', NULL),
        (32, 9, 'Travel (Domestic, International)', NULL),
        (33, 9, 'Hotel Stay', NULL),
        (34, 9, 'Car Service', NULL),
        (35, 9, 'Car Maintenance', NULL),
        (36, 9, 'Bike Repairs', NULL),
        (37, 9, 'Fuel', NULL),
        (38, 10, 'Salary', NULL),
        (39, 10, 'Dividends from stocks', NULL),
        (40, 10, 'FD Sweeps', NULL),
        (41, 10, 'Other Income', NULL),
        (42, 6, 'Upskilling', NULL),
        (43, 9, 'Birthday celebrations', NULL);